### ISSUE TITLE
Here is my insight on this idea.

### ISSUE THREAD

**Issue by Cum6upck** [simtechdev/smtk-deploy#3]
This tool will not be a universal solution due to the following reasons:
-  Different versions of CS-Cart use different PHP versions. This script will be run on the developer’s computer and has a bottom limit for PHP version, which is 5.5.х. At the same time CS-Cart versions 2.х and 3.х can work only on PHP versions 5.3.х - 5.4.х ;
- If development is performed with visualization tools (for example, VirtualBox) or on a separate server, there is no point in having a PHP interpreter just because of one script.

My suggestion is to implement the deployment toolkit in the inner script language of ОС Linux, like python (it exists in any ОС Linux and can be easily deployed on MacOS and Windows) or bash interpreter. The advantage of the python language over bash is that it has OOP paradigm, which will allow to divide functionality into add-ons and activate them one by one.

If we are not able to use my solution, you should use PHPBrew instead.

**Comment by gongled** [comment]
Thank you for your reply. I suppose we don't want to use Python as a main language to develop `deploy-toolkit`. The main reason is giant difference between 2.x and 3.x – it's not so easy to maintain. Anyway, I'm totally agree with you, PHP 5.5 is a serious limiting factor. So we're going to try Capistrano 3 and create new prototype on Ruby.

**Comment by Cum6upck** [comment]
I offer use a programming language which is closer to web then Ruby. Instead of Capistrano 3 I offer use Shipit Node.js.
Also we can use Maven as deploy tool. It tool was made with java (every OS has one) and it contains deploy tool in xml file. This variant don't require the knowledge of any programming language for deployment.

**Comment by gongled** [comment]
We decided to continue working under the project with PHP interpreter. The main reason is our team able to support PHP applications whereas other languages are not so popular in development cycle. For those who plan use utility with preinstalled PHP 5.3 we will prepare Docker image and simple wrapper to execute the same commands inside container.
